### PR TITLE
Custom Maps via Configuration File

### PR DESCRIPTION
**Pull request by jimbo8098**
This PR adds the ability to configure custom maps without needing to enter the individual configuration files, thus allowing for quick changes to be made to the KF2 map list through a server restart. 

The change adds Ruby code to take a game.yml file containing a list of custom maps and simply templates all the configuration in meaning no more adding code to the server. Examples are listed in the README.md file demonstrating how this works.

Other changes:

- Added docker- and gitignore files to exclude private files.
- Moving to Focal from Xenial in order to support latest server binaries.

My main worry with this PR is the Default Maps deviating from the expected config used by KF2 in cases where a new map is released. I will look into writing Travis tests for this in due course.

### CODE REVIEW

**Comment by jimbo8098** [comment]
I've been testing this branch for months now with no issue btw ;)

**Comment by dwurf** [comment]
Thanks @jimbo8098, I appreciate the work you've done on this. I've been thinking about something like this for a while now, my loose plan was to generate the official map list from the maps on disk, and blacklisting the random lobby / menu ones.

I'll take a look at this one soon (weekend probably) since there's a bit to unpack here.

**Comment by jimbo8098** [comment]
I think it does what you're looking for then! My idea pretty much matched your own; to create the map list automatically. This should reduce time to deploy new maps which, in my case, it achieves quite well. We can expand on the templating rather easily with it in this state. One of the things I'd planned to do was add a motto using the same template engine.

I have that PR waiting once this is approved but I wanted to make sure we were on the same page before going down that particularly dark rabbit hole :joy:

**Comment by dwurf** [comment]
I dropped the ball on this. Merging it now.

**Pull request merged**
